name: git check
on: [push]
jobs:
  check:
    runs-on: ubuntu-18.04
    steps:
    - name: check out code
      uses: actions/checkout@v1
    - name: print git branch
      run: git symbolic-ref --short HEAD
